version: 2
updates:
    - package-ecosystem: 'pip'
      directory: '/02'
      schedule:
          interval: 'daily'
      allow:
          - dependency-type: 'all'
      target-branch: 'main'
    - package-ecosystem: 'composer'
      directory: '/03'
      schedule:
          interval: 'daily'
      allow:
          - dependency-type: 'all'
      labels:
          - 'Updated by dependabot'
      versioning-strategy: increase
    - package-ecosystem: 'npm'
      directory: '/04'
      schedule:
          interval: 'daily'
      allow:
          - dependency-type: 'production'
      ignore:
          - dependency-name: 'axios'
      labels:
          - 'Updated by dependabot'
      versioning-strategy: increase
